language: elixir

elixir:
  - '1.7.4'
otp_release: '20.3'

script:
  - mix credo
  - mix format --check-formatted
  - mix test --no-start
  - mix docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: doc
  on:
    branch: master
